# File: docker/Dockerfile.radius
FROM golang:1.24.3-alpine

WORKDIR /app

RUN apk add --no-cache tzdata

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o radius-controlplane ./cmd/radius-controlplane

EXPOSE 1813/udp

ENTRYPOINT ["/app/radius-controlplane"]
