
services:
  redis:
    image: redis:7-alpine
    container_name: redis
    command: redis-server --notify-keyspace-events KEA
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  radius-controlplane:
    build:
      context: ..
      dockerfile: docker/Dockerfile.radius
    container_name: radius-controlplane
    environment:
      - RADIUS_SECRET=testing123
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
      - LOG_FILE_PATH=/var/log/radius_server.log
    depends_on:
      - redis
    ports:
      - "1813:1813/udp"
    volumes:
      - ./persisted_logs:/var/log

  redis-controlplane-logger:
    build:
      context: ..
      dockerfile: docker/Dockerfile.subscriber
    container_name: redis-controlplane-logger
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
      - LOG_FILE_PATH=/var/log/radius_logger.log
    depends_on:
      - redis
    volumes:
      - ./persisted_logs:/var/log

  radclient-test:
    build:
      context: ..
      dockerfile: docker/Dockerfile.radclient
    container_name: radclient-test
    stdin_open: true
    tty: true
    depends_on:
      - radius-controlplane

volumes:
  redis-data:
