# File: docker/Dockerfile.subscriber
FROM golang:1.24.3-alpine

WORKDIR /app

RUN apk add --no-cache tzdata

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o redis-controlplane-logger ./cmd/redis-controlplane-logger

ENTRYPOINT ["/app/redis-controlplane-logger"]
